name = "games/untilted_game"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dependencies]
promise = { wally = "evaera/promise", version = "^4.0.0" }
unzip = { name = "0x5eal/unzip", version = "^0.2.0", target = "luau" }
greentea_luau = { name = "jiwonz/greentea_luau", version = "^0.2.0", target = "luau" }
luau_disk = { name = "jiwonz/luau_disk", version = "^0.2.0", target = "luau" }
react = { wally = "jsdotlua/react", version = "^17.2.1" }
react-roblox = { wally = "jsdotlua/react-roblox", version = "^17.2.1" }
sift = { wally = "csqrl/sift", version = "^0.0.11" }
bytenet = { wally = "ffrostflame/bytenet", version = "^0.4.6" }
trove = { wally = "sleitnick/trove", version = "^1.8.0" }
typed-promise = { wally = "lukadev-0/typed-promise", version = "^4.0.2" }
logging = { wally = "ozzypig/logging", version = "^0.3.0" }


[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
