[tools]
rojo = "rojo-rbx/rojo@7.6.1"
pesde = "pesde-pkg/pesde@0.7.2+registry.0.2.3"
lune = "lune-org/lune@0.10.4"
stylua = "johnnymorganz/stylua@2.3.1"
selene = "kampfkarren/selene@0.29.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
