std = "roblox"

exclude = [
    ".pesde/**",
    "roblox_packages/**",
    "node_modules/**",
    "lune_packages/**",
    "luau_packages/**",
    "**/.pesde/**",
    "**/roblox_packages/**",
]

[rules]
incorrect_standard_library_use = "allow"
